### ISSUE TITLE
Research deploying multiple MinIO tenants, each with separate storage backends

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#503]
As a collaborator at SickKids, I want to use my own storage allocation for uploading datasets so that I can keep my data in my space and avoid using space in the CCM allocation. I also want to be able to access files as they are on the storage backend so that I can directly pass them to bioinformatics pipelines on HPF.

MinIO provides a multitenant distributed deployment guide [here](https://docs.min.io/docs/multi-tenant-minio-deployment-guide.html). Unfortunately, this leans heavily into an erasure-coding configuration, which is undesirable because we cannot satisfy the second element of the user story. We do not need erasure coding as our underlying storage infrastructure already takes care of those concerns.

This means that we can either deploy one "erasure-coded" instance per tenant, or any number of load-balanced NAS Gateway instances per tenant. In the former case, we cannot run multiple such instances on the same storage backend as one will lock it for its exclusive use. In the second case, we can since it is only acting as a gateway, but we will not be able to make use of the Console until a future update (I think). In the second case, we would also be able to achieve higher availability and zero downtime through rolling upgrades. Zero downtime is not a strict requirement because the MinIO process restarts very quickly and S3-aware clients will use multipart uploads for large files and automatically retry as needed.

**Comment by samuelkimuli** [comment]
Am encountering a certain error whenever am trying to join a node to a swarm, this is likely due to the following:
1. TCP and UDP port 7946 for communication among nodes , and 
2. UDP port 4789 for overlay network traffic 
The two ports might not be enabled in the CCM testing cluster, i currently have no administrative rights to alter security groups there

Alternatively it could probably due to the fact that since  the generated token (to join a cluster) is dependent of the time, the workers might need  to syncronize their time with the manager node  perhaps by using NTP.
Despite all that , timedatectl command shows consistent time across all workers and the manager.

Take a look at this identical problem  https://forums.docker.com/t/fail-join-node-as-worker/48321

**Comment by kevinlul** [comment]
On Friday we discovered that to use the admin API and multiple users in a distributed or NAS gateway configuration, an [external distributed key-value store](https://docs.min.io/docs/minio-multi-user-quickstart-guide.html) is required like [etcd](https://github.com/minio/minio/blob/master/docs/sts/etcd.md). This should also be part of our deployment.

**Comment by samuelkimuli** [comment]
Considering running multiple load-balanced NAS Gateway instances per tenant doesn't work because the entire admin API doesn't work in gateway mode, including multi-user. This would require another etcd server for dealing with credentials in a distributed fashion. Clustering etcd requires swarm or kubernetes. I was in the process of running it with kubernetes  using nfs as the storage provisioner (according to our usecase) , after some conversations with a member of the minio team , he pointed out that running minio with kubernetes and nfs as the storage provisioner in this distributed fashion is not supported "nfs volumes for distributed setups is not supported, it may work but would highly recommend against it, performance and stability being at the top of the list" .
