### ISSUE TITLE
Assemble current DCC Forge reports into variant viewer database (static one-time)

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#580]

**Comment by delvinso** [comment]
@kevinlul  - see https://github.com/ccmbioinfo/sampletracker2stager/pull/6

Not sure if it matters but I just realized I added the scripts necessary for populating the gene and gene alias tables as part of that PR even though it's a separate issue. 

~1138 reports mapped out of 1500 - the remaining are unmapped due to a combination of family and participant codenames/aliases not being found, as well as inconsistent result paths. The reports that are mapped may not be perfect (see limitations/assumptions made in map_insert_c4r_reports.py).
