### ISSUE TITLE
Flask: remove pandas dependency

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#914]
`pandas` is used in a few places in the backend, mainly to work with CSVs as a data frame and also read in the results of a SQL query for that end. pandas and dependency numpy weigh 118 MB, or a third of the final image size (330 MB), and a majority of the layers added by us (`python:3.7-slim` is 120 MB).

If we have time, we should look at achieving the same functionality with the standard library and existing dependencies. The extra size only increases deployment time when Python dependencies are updated.

**Comment by jennyziyi-xu** [comment]
A breakdown of our final image (330MB), ignoring the dependencies in the KB range. 

1.5M	alembic
1.9M	werkzeug
2.0M	_pytest
2.1M	astroid
2.4M	authlib
2.7M	typed_ast
2.8M	pytz
2.8M	tzdata
2.9M	pylint
2.9M	regex
2.9M	setuptools
9.5M	pip
11M	        cryptography
13M	        sqlalchemy
14M	        debugpy
30M	        numpy
33M	        numpy.libs
57M	        pandas

**Comment by jennyziyi-xu** [comment]
`pandas` is used in `manage.py`, `mapping_utils.py`, `routes.py`, `variants.py` and `test_variants.py`

How is `pandas` used?
- `pd.DataFrame()`
- `pd.read_csv()`
- `to_csv()`
- `pd.read_sql()`
-  In most cases, pandas is used to convert a csv report to a Pandas DataFrame for data processing and iterating through the data, in order to create objects to be inserted into the database. 

I think that 
- Pandas provides clean API, and is more reliable than manually constructing a dictionary with `csv` built-in methods.
- Processing CSV reports is an important part of Stager, so if we can afford to have pandas, that's better. 
- If we really want to remove pandas, we can use `csv.reader()` and `csv.writer()` to convert a csv report into a dictionary, and do data processing on the dictionary. 
- `numpy` is used only for accessing `np.nan` types. Should we consider **removing numpy** dependency and check for NaN in another way?

**Comment by jennyziyi-xu** [comment]
`numpy.libs` contains: 
-rwxr-xr-x 1 root root  2223184 Dec  9 20:55 libgfortran-2e0d59d6.so.5.0.0
-rwxr-xr-x 1 root root 31691664 Dec  9 20:55 libopenblasp-r0-2d23e62b.3.17.so
-rwxr-xr-x 1 root root   263992 Dec  9 20:55 libquadmath-2d0c479f.so.0.0.0

I think these are necessary dynamic links for numpy dependencies, and there's no problem here. Just putting it here in case this is not something we expected.

**Comment by jennyziyi-xu** [comment]
Jenny's conclusion:

- Handling CSV report ( reading it in to manipulate data + outputting to CSV report ) is an important part of Stager. Pandas is a standard way to handle these kinds of operations, so I would retain pandas.
- Regarding the [current attempt](https://github.com/ccmbioinfo/stager/commit/0e286b8617b93765af1f0c1d6716e6620c4b62d1 ) to write a custom library: 
The current attempt only contains data manipulation-related functions, it doesn’t contain functionalities to read in from a CSV file and output to a CSV file. I would say this custom library would be more error-prone than pandas library.
